#ifndef _MCAL_TIM0_CONFIG_H_
    #define _MCAL_TIM0_CONFIG_H_
/*
Options of TIM0_MODE :
    0 => NORMAL MODE
    1 => PHASE PWM MODE
    2 => CTC MODE
    3 => FAST PWM MODE
    4 => NON-PWM MODE
*/

#define TIM0_MODE   3 


/*
Options of TIM0_COM_NONPWM :
        0X00 => NORMAL PORT OPERATION
        0X10 => TOGGLE OC0 ON COMPARE MATCH
        0X20 => CLEAR OC0 ON COMPARE MATCH
        0X30 => SET OC0 ON COMPARE MATCH
       
*/

#define TIM0_COM_NONPWM   0X00 

/*
Options of TIM0_COM_FASTPWM :
        0X00 => NORMAL PORT OPERATION
        0X20 => CLEAR OC0 ON COMPARE MATCH AND SET ON BOTTOM
        0X30 => SET OC0 ON COMPARE MATCH AND CLEAR ON BOTTOM
       
*/
#define TIM0_COM_FASTPWM   0X30 


/*
Options of TIM0_COM_PCPWM :
        0X00 => NORMAL PORT OPERATION
        0X20 => CLEAR OC0 ON COMPARE MATCH ON UPCOUNT AND SET ON COMPARE MATCH ON DOWNCOUNT
        0X30 => SET OC0 ON COMPARE MATCH ON UPCOUNT AND CLEAR ON COMPARE MATCH ON DOWNCOUNT
       
*/
#define TIM0_COM_PCPWM   0X00 



/*
Options of TIM0_COM_NONPWM :
        0 => DISABLE FOC0
        1 => ENABLE FOC0
       
*/
#define TIM0_FOC0 0



/*
Options of TIM0_COM_NONPWM :
        0 => DISABLE OVERFLOW INTERRUPT
        1 => ENABLE OVERFLOW INTERRUPT
       
*/
#define TIM0_TOVINT 0

/*
Options of TIM0_COM_NONPWM :
        0 => DISABLE COMAPRE MATCH INTERRUPT
        1 => ENABLE COMAPRE MATCH INTERRUPT
       
*/
#define TIM0_TOCINT 0

#endif